# Research: Segmentasi Area Kebakaran Hutan dan Lahan pada Citra Satelit
# Menggunakan DeepLabV3+ dengan Backbone MobileViT untuk Wilayah Tropis Indonesia
#
# Test-time augmentation (TTA) for segmentation.
#
# Averages predictions over the 8 dihedral (D4) orientations of the input — the
# symmetry group generated by the horizontal flip and the 90° rotation already
# used during training (see the datamodule augmentation). For square satellite
# tiles with no canonical orientation this is the principled, information-
# preserving augmentation set, and it typically adds a small IoU/F1 gain at
# inference with NO retraining (each orientation is predicted, mapped back to the
# original frame, and the class probabilities are averaged).

import torch


def _make_d4_transforms():
    """Build the 8 (forward, inverse) transform pairs of the D4 group.

    Each forward maps an input into one orientation; its inverse maps a spatial
    prediction from that orientation back to the original frame, so predictions
    can be averaged in a common frame. ``inverse(forward(x)) == x`` for all 8
    (verified in the tests), which is what makes the averaging valid.
    """
    transforms = []
    for flipped in (False, True):
        for k in range(4):
            def fwd(x, k=k, flipped=flipped):
                if flipped:
                    x = torch.flip(x, dims=[-1])
                return torch.rot90(x, k, dims=[-2, -1])

            def inv(y, k=k, flipped=flipped):
                y = torch.rot90(y, -k, dims=[-2, -1])
                if flipped:
                    y = torch.flip(y, dims=[-1])
                return y

            transforms.append((fwd, inv))
    return transforms


D4_TRANSFORMS = _make_d4_transforms()


@torch.no_grad()
def tta_predict(forward_fn, x, transforms=None, softmax=True):
    """
    Average model predictions over spatial transforms (default: the D4 group).

    Parameters
    ----------
    forward_fn : callable
        Maps an input batch (B, C, H, W) to logits (B, n_classes, H, W).
    x : torch.Tensor
        Input batch.
    transforms : list of (forward, inverse) callables, optional
        Defaults to the 8-element D4 group (4 rotations × optional h-flip).
    softmax : bool
        If True, average class probabilities (softmax over dim=1); otherwise
        average raw logits. Probabilities are the usual, better-behaved choice.

    Returns
    -------
    torch.Tensor
        Averaged predictions (B, n_classes, H, W). Take ``argmax(dim=1)`` for a
        hard segmentation mask.
    """
    if transforms is None:
        transforms = D4_TRANSFORMS

    accum = None
    for fwd, inv in transforms:
        out = forward_fn(fwd(x))
        if softmax:
            out = torch.softmax(out, dim=1)
        out = inv(out)
        accum = out if accum is None else accum + out
    return accum / len(transforms)
